sudo: required

env:
  DOCKER_COMPOSE_VERSION: 1.8.0

services:
  - docker

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` | sudo tee /usr/local/bin/docker-compose > /dev/null
  - sudo chmod +x /usr/local/bin/docker-compose


script:
  - export TZ=Europe/London
  - travis_retry ./runtests-ci.sh
