version: '2'
services:
  test:
    depends_on:
     - backend
     - frontend
  backend:
    build: be
    expose:
      - 8080
    environment:
     - NODE_ENV=development
     - PORT=8080
  frontend:
    build: fe
    expose:
     - 80
    environment:
     - BACKEND=http://backend:8080
     - PORT=80