version: '2'
services:
  waiter:
    image: martin/wait
    depends_on:
      - selenium
    environment:
      - selenium_TCP=tcp://selenium:4444
  test:
    build: .
    volumes:
      - ./nightwatch/reports:/home/app/reports
      - ./nightwatch/screenshots:/home/app/screenshots
    env_file: mycredentials
    environment:
      - SELENIUM_HOST=selenium
  selenium:
    image: selenium/standalone-chrome:2.53.0
    expose:
      - 4444
    environment:
      - SCREEN_WIDTH=1024
      - SCREEN_HEIGHT=768
      - SCREEN_DEPTH=24