source 'https://rubygems.org'

group :test do
  # BDD for Ruby
  gem 'rspec', '3.2.0'
  gem 'rspec-expectations', '3.2.0'
  # BDD using gherkin
  gem 'cucumber', '2.0.0'
  # user based testing framework/helper
  gem 'capybara', '2.5.0'
  # headless browser used by capybara
  gem 'poltergeist', '1.7.0'
  # in-browser test framework
  gem 'selenium-webdriver', '2.48.0'
  # a gem to create a new file in the Excel 2007+ XLSX format.
  gem 'write_xlsx','0.83.0'
  # Roo can access the contents of various spreadsheet files
  gem 'roo', '2.2.0'
  # pdf reader
  gem 'pdf-reader','1.3.3'
  # HTTP/REST API client library.
  gem 'faraday', '0.9.2'
  gem 'faraday_middleware', '0.10.0'
  # requires all files in a directory
  gem 'require_all', '1.3.3'
  # read write json files
  gem 'json', '1.8.3'
  # ruby core extension
  gem 'activesupport', '4.2.4'
  # cookie extraction
  gem 'show_me_the_cookies', '3.1.0'
end